server:
  port: 8888
  shutdown: graceful
  protocol: http
  domain: localhost
  prefix-path: /schedule
  developer-mail: byoungkyu.so@saltlux.com # 중요 에러 시 메일 발송

data-org: # data.org
  spcdeinfoservice:  # 특일 정보제공 서비스
    url: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
    service-key: 4fncWMhVhrVNoXU0I1UYVdavnsjvHPdGJQT8yRI2YMKvYerCKgEXcky1v2C1ByQYe9g0%2FrpdYZk3w6DYpiLFHg%3D%3D # bgso777 개인 개정의 인증키
    operations: getHoliDeInfo,getRestDeInfo,getAnniversaryInfo # getHoliDeInfo: 국경일,  getRestDeInfo: 공휴일,  getAnniversaryInfo 기념일

calandar:
  holiday:
    temporary:
      name: 추석,설날,임시,대체

logging:
  config: classpath:log4j2/log4j2-${spring.config.activate.on-profile}.xml
  level:
    root: debug
  multifile:
    useyn: false

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health: check
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

spring:
  application:
    name: scheduler
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://10.0.11.30:3306/aice?useSSL=false&amp;characterEncoding=utf8
    username: be_account
    password: 67606CF147BE4745AC2194EF9831BE1DBF3ECA9C2B554EE79E620DC9AD52D027
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout : 30000 # 최대 3초까지만 pool 대기
      maximumPoolSize : 3
      connectionTestQuery : select 1
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    ddl-auto: none # update the schema with the given values
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        allow_update_outside_transaction: true
    generate-ddl: true
    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src
  jackson:
    parser:
      allow-unquoted-field-names: true
      allow-single-quotes: true
    serialization:
      INDENT_OUTPUT: true
  security:
    filter:
      ips: 0:0:0:0:0:0:0:1,127.0.0.1,localhost
  mail:
    host: outlook.office365.com
    port: 587
    username: aice@saltlux.com
    password: MsCy9jC4QyceCNS
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

