server:
  port: 8989
  shutdown: graceful
  protocol: http
  domain: localhost
  prefix-path: /litten/anon/svc
  developer-mail: byoungkyu.so@saltlux.com # 중요 에러 시 메일 발송
  servlet:
    context-path: /litten

  billing-url: http://localhost:8787/aice/billing
  #  config-manager-url: http://localhost:8151/aice/configManager
  config-manager-url: http://10.0.131.55:8151/aice/configManager
  #  talkbot-url: http://localhost:4001
  talkbot-url: http://192.168.220.222:4001
  #  message-url: http://10.0.131.55:8282/aice/msggw/messages/v1/send/sms
  message-url: https://dev-backdoor.ploonet.com/message-gateway/aice/msggw/messages/v1/send/sms
  message-kakao-url: https://dev-backdoor.ploonet.com/message-gateway/aice/msggw/messages/v1/send/bulk/kakao
  union-url: http://localhost:8161


logging:
  config: classpath:log4j2/log4j2-${spring.config.activate.on-profile}.xml
  level:
    root: debug
  multifile:
    useyn: false

management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health: check
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

spring:
  freemarker:
    suffix=: .ftl
  application:
    name: accountManager
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/litten?autoReconnect=true
    username: litten
    password: litten1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout : 30000 # 최대 3초까지만 pool 대기
      maximumPoolSize : 3
      connectionTestQuery : select 1
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    ddl-auto: none # update the schema with the given values
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        allow_update_outside_transaction: true
    generate-ddl: true
#    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src
  jackson:
    parser:
      allow-unquoted-field-names: true
      allow-single-quotes: true
    serialization:
      INDENT_OUTPUT: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  security:
    filter:
      ips: 0:0:0:0:0:0:0:1,127.0.0.1,localhost
#  mail:
#    host: smtp-mail.outlook.com
#    port: 587
#    username: company@ploonet.com
#    password: ploonet@0425
#    ssl.used: N
#    starttls.enable: Y
#    properties:
#      mail:
#        debug: true
#        smtp:
#          connectiontimeout: 30000
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            protocols: TLSv1.2
  mail:
    host: outlook.office365.com
    port: 587
    username: aice@saltlux.com
    password: MsCy9jC4QyceCNS
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2

#  datasource-ploonettotal:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/ploonet_total?autoReconnect=true
#    username: aice
#    password: aice1234
#  rabbitmq:
#    signup:
#      exchange: v1.ex.events
#      routionkey: v1.events.account.join
#    signup-fail:
#      exchange: v1.ex.events
#      routionkey: v1.events.account.join
#    withdraw:
#      exchange: v1.ex.events
#      routionkey: v1.events.account.leave
#    withdraw-fail:
#      exchange: v1.ex.events
#      routionkey: v1.events.account.leave

jwt:
  token-validity-in-milliseconds: 43200000 # 600000(10분), 43200000(12시간), 86400000(24시간), 31536000000(365일)
  mobile-token-validity-in-milliseconds: 2592000000 # 모바일용 30일
  secret: aiceaccountjwtsecretparsetargettobase64

cs-center-company-seq: 651
